//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecoRP_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionToApplications
    {
        public int QuestionID { get; set; }
        public int ApplicationID { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
