//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecoRP_Debugger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int AnswerId { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<byte> Answer { get; set; }
        public string AnswerText { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
