//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecoRP_Debugger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blogs
    {
        public int BlogId { get; set; }
        public string URL { get; set; }
        public string ImageURL { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<byte> CategoryId { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
