//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecoRP_Debugger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeOffers
    {
        public int OfferId { get; set; }
        public int TradeCategoryId { get; set; }
        public string OfferOwnerUserID { get; set; }
        public string OfferOwnerSocialClubID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string ImageURL { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual TradeCategories TradeCategories { get; set; }
    }
}
